# Generated by Django 3.2.18 on 2023-02-18 12:26

import clickhouse_backend.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', clickhouse_backend.models.fields.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
