# Generated by Django 3.2.18 on 2023-02-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('s_0', models.FloatField(null=True)),
                ('s_0_0', models.FloatField(null=True)),
                ('s_0_1', models.FloatField(null=True)),
                ('s_1', models.FloatField(null=True)),
                ('s_1_0', models.FloatField(null=True)),
                ('s_1_1', models.FloatField(null=True)),
                ('s_1_2', models.FloatField(null=True)),
                ('s_1_3', models.FloatField(null=True)),
                ('s_1_4', models.FloatField(null=True)),
                ('s_1_5', models.FloatField(null=True)),
                ('s_1_6', models.FloatField(null=True)),
                ('s_1_7', models.FloatField(null=True)),
                ('s_1_8', models.FloatField(null=True)),
                ('s_1_9', models.FloatField(null=True)),
                ('s_2', models.FloatField(null=True)),
                ('s_2_0', models.FloatField(null=True)),
                ('s_2_1', models.FloatField(null=True)),
                ('s_3', models.FloatField(null=True)),
                ('s_4', models.FloatField(null=True)),
                ('s_4_0', models.FloatField(null=True)),
                ('s_4_1', models.FloatField(null=True)),
                ('s_4_2', models.FloatField(null=True)),
                ('s_4_3', models.FloatField(null=True)),
                ('s_4_4', models.FloatField(null=True)),
                ('s_4_5', models.FloatField(null=True)),
                ('s_4_6', models.FloatField(null=True)),
                ('s_4_7', models.FloatField(null=True)),
                ('s_4_8', models.FloatField(null=True)),
                ('s_4_9', models.FloatField(null=True)),
                ('s_5', models.FloatField(null=True)),
                ('s_5_0', models.FloatField(null=True)),
                ('s_5_1', models.FloatField(null=True)),
                ('s_5_2', models.FloatField(null=True)),
                ('s_5_3', models.FloatField(null=True)),
                ('s_5_4', models.FloatField(null=True)),
                ('s_5_5', models.FloatField(null=True)),
                ('s_5_6', models.FloatField(null=True)),
                ('s_5_7', models.FloatField(null=True)),
                ('s_5_8', models.FloatField(null=True)),
                ('s_5_9', models.FloatField(null=True)),
                ('s_6', models.FloatField(null=True)),
                ('s_6_0', models.FloatField(null=True)),
                ('s_7', models.FloatField(null=True)),
                ('s_7_0', models.FloatField(null=True)),
                ('s_8', models.FloatField(null=True)),
                ('s_8_0', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_machine', models.CharField(max_length=255, null=True)),
                ('parent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SensorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sensor', models.CharField(max_length=255, null=True)),
                ('parent', models.IntegerField()),
                ('unit', models.CharField(max_length=255, null=True)),
                ('last', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SignalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(choices=[('ANAL', 0), ('DIGITAL', 1)], max_length=255)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kafka_app.machinemodel')),
                ('sensor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kafka_app.sensormodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
