# Generated by Django 3.2.18 on 2023-02-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0004_auto_20230218_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinemodel',
            old_name='name_machine',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sensormodel',
            old_name='name_sensor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='signalmodel',
            old_name='sensor',
            new_name='id_sensor',
        ),
        migrations.RemoveField(
            model_name='signalmodel',
            name='exhauster',
        ),
        migrations.AddField(
            model_name='signalmodel',
            name='id_exhauster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exhauster', to='kafka_app.machinemodel'),
        ),
    ]
