# Generated by Django 3.2.18 on 2023-02-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_app', '0005_auto_20230218_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kafkadatamodel',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='kafkadatamodel',
            name='s_0c26',
        ),
        migrations.RemoveField(
            model_name='kafkadatamodel',
            name='s_2c26',
        ),
        migrations.RemoveField(
            model_name='kafkadatamodel',
            name='s_3c26',
        ),
        migrations.AddField(
            model_name='kafkadatamodel',
            name='moment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
